.travis.yml
RefRed/version.py
scripts/RefRed
scripts/start_refred.py
setup.cfg

This changes the RefRed rpm to depend on Mantid 4.2.
Updated startup script until I could successfully start RefRed on the analysis computer.

Fix mantid version to 4.2

---

.gitignore
RefRed/interfaces/sf_calculator_interface.py
RefRed/sf_calculator/load_and_sort_nxsdata_for_sf_calculator.py
RefRed/sf_calculator/sf_calculator.py
RefRed/version.py
designer/sf_calculator_interface.ui

This PR made the following changes to the app `scaling_factor_calculator`:
- The default sorting method upon data loading is __by run number__.
- A new button `sort` is added, which will force reload and sort the table by metadata (previous method)
> NOTE:
The motivation behind this PR is that the current sort by metadata is broken, which prevents the app from generating correct scaling factor.
The beamline scientist are using run number to bypass this issue for newer data, which is by the default sorting is switched to __by run number__.
The long term solution would be fixing the metadata-based sorting, but it is beyond the scope of this PR.
> closes #8

Issue 16 l rscale factor error

---

RefRed/configuration/loading_configuration.py

To change the view mode to not display additional metadata, the static function from QFileDialog needed to change to a manual dialog setup. This requirement is derived from the ViewMode being an option separate from all other options in the static function and setup. With this change, the configuration file browser should now display without file size or last modified date.

Refl 47 config file browser

---

RefRed/gui_handling/fill_stitching_table.py
RefRed/interfaces/mplwidgets.py
RefRed/plot/display_plots.py
RefRed/plot/popup_plot_1d.py
RefRed/plot/popup_plot_2d.py
RefRed/reduction/live_reduced_data_handler.py
RefRed/reduction/reduced_data_handler.py
RefRed/sf_calculator/sf_calculator.py

- Original Gitlab task: [REF181](https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/181)
This PR introduces the following improvements:
- removed the reset of cursor and upgrade `canvas.draw()` to `canvas.draw_idle()` as suggested by Matplotlib
- resolved an importing error due to API change between Qt4 and Qt5
- resolved an issue caused by calling a deprecated API in `QTableWidgetItem`
Known issue:
- The `sort` button in the sf_calculator leads to a crash.  After reviewing the source code, it does not seem like this feature was fully implemented to begin with. Additional work (outside of this PR) is needed to address this issue.

Fix app crash during active update of figure

---

RefRed/decorators.py

The usage is to add the decorator above a function call to see thevalues that are passed in via the value's `__repr__` method. Clients need to know which kind of function is being called and select the correct decorator.
Example usage for qt slot
```python
@log_qtpy_slot
def reset_button(self):
"""reset all the settings to default value hard coded in program"""
o_list_settings = ListSettings()
_list_keys = list(o_list_settings.__dict__.keys())
...
```
Example usage for member method
```python
class ListSettings(object):
@log_method
def __init__(self):
self.q_min = 0.005
self.d_q0 = 0.0004
self.dq_over_q = 0.005
self.tof_bin = 40  # micros
self.q_bin = 0.01  # logarithmic binning
self.clocking_pixel = [121, 197]
self.angle_offset = 0.016
self.angle_offset_error = 0.001
```
Example usage of …

Add decorators to optionally log function signatures

---

RefRed/sf_calculator/lr_data.py

This reduces the memory usage of test/ui/test_compute_scaling_factors.py to about 70% of before.

First pass of reducing memory usage in sf_calculator during loading

---

requirements_dev.txt
setup.py

`pytest-runner` is deprecated, see https://github.com/pytest-dev/pytest-runner/blob/main/README.rst#deprecation-notice
`tests_require` in `setup.py` is deprecated, see https://github.com/pypa/setuptools/issues/1684
`pytest-mock` and `pytest-xdist` are unused.

Remove deprecated and unused dependencies

---

RefRed/interfaces/plot_dialog_refl_interface.ui
RefRed/plot/popup_plot_1d.py
test/ui/test_popup_plot_1d.py

**Description of work.**
PR addresses the depreciation of the John plot, replacing it with just the Jim plot under a different name.
**To test:**
Run the program and load a configuration from the `test/data` directory.
In the table on the bottom right check at least of of the rows as "plotted" by clicking the checkbox in the left most column.
Data should appear on the charts on the top right, click on the right most chart to open the pop up that used to contain the Jim and John plots.  There should just be one plot now.  Test to see if it functions as before but with just the on chart.
Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):
- Is the code of an acceptable quality?
- Does the code conform to the [coding …

removed john, renamed instances of jim to plot

---

RefRed/metadata/metadata_finder.py

Ask QSettings if `nbr_metadata` exists before fetring the value and trying to use it.
Also fix a crash when an invalid run number is specified. To test, try run 1234. 
[Defect description](https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/238)

Fix problem when QSettings are missing

---

RefRed/calculations/lr_data.py

- Original Gitlab Defect: [REF237](https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/237)
This PR fixes an incorrect refactoring of `lr_data.countsxdata` during the modernization.
The fix is derived from pre-modernization version and should produce the correct `lr_data.countsxdata`.

correct countsxdata from lr_data

---

RefRed/__init__.py
RefRed/about_dialog.py
RefRed/decorators.py
RefRed/gui_handling/gui_utility.py
RefRed/initialization/gui.py
RefRed/reduction_table_handling/reduction_table_handler.py
RefRed/version.py
scripts/start_refred.py

Versioneer was not used in the about dialog and the file `RefRed/version.py` was a potential point of confusion for future development. This moves everything to use the `__version__` supplied by versioneer and removes the old versioning mechanism.

Standardize version

---

.github/workflows/conda_env/environment.yml
RefRed/gui_handling/fill_stitching_table.py

QBrush doesn't work in newer versions of pyqt5, user QColor instead
Fixes https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/285

Fix SF colour

---

.github/workflows/test-and-deploy.yml

As a side benefit, failed triggers will fail the build.

Update triggers to use the standard methods

---

RefRed/sf_calculator/lr_data.py

- Original Defect: [REF186](https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/186)
In PR #67, the workspace attr for LRData is removed, which leads to the crash of SF calculator when the sort button is clicked.
This PR revert the single change and the crash issue should be resolved.
Testing guideline:
For those who wants to test the change without waiting for the deployment,
- on analysis cluster, clone this branch.
- make sure the system conda environment is disabled so as to avoid calling the wrong dependencies.
- setup a local dev env using either local conda or micromamba (recommended)
- make sure install `mantidworkbench` in the test env, which provides most of the dependencies
- install `configobj` from conda-forge
- do an editable install for this branch with …

[REF186] Resolve missing workspace attr related crash of SF_Calculator

---

.github/workflows/test-and-deploy.yml

(Copied from [iMars3D PR "Trouble shoot CI failure related to Github mamba solution"](https://github.com/ornlneutronimaging/iMars3D/pull/281))
The issue is at the upstream where the provider's mamba solution is also failing (https://github.com/conda-incubator/setup-miniconda/actions/runs/3944571519/jobs/6750622433).
The goal here is to find a temp solution until the provider fixes their issue.
The workaround solution is found in this issue: https://github.com/conda-incubator/setup-miniconda/issues/274

Trouble shoot CI failure related to Github mamba solution 

---

RefRed/reduction/global_reduction_settings_handler.py

One of the reduction parameters was captured in the interface but was never used. This PR adds it to the list of reduction parameters.

Add missing reduction parameter

---

.github/workflows/conda_env/environment.yml
RefRed/configuration/export_xml_config.py
RefRed/configuration/loading_configuration.py
RefRed/interfaces/refred_main_interface.ui
RefRed/reduction/global_reduction_settings_handler.py
RefRed/reduction/individual_reduction_settings_handler.py
release_notes.md
requirements.txt
test/unit/RefRed/configuration/test_loading_configuration.py

Some of the options in the UI were ignored and not saved in the config file.
- The normalization option (which is a global option in the current UI) was ignored. It's now also saved properly.
- The boolean options in the config file were ignored because they were not loaded properly.
- The table headers on the main page were missing.
- The Settings panel is no longer useful and has been hidden until we refactor the configuration.
- A typo made the background subtraction option default to true.
- Adding release notes

Fix reduction options

---

RefRed/configuration/loading_configuration.py

This PR updates the message shown to a user who loads a template produced by the previous refred version.
It accurately tells the user how to start the v4 version.

Update warning message for legacy reduction

---

requirements.txt

We need to update the reduction package to the latest version so that we can perform free liquid experiments and reduce data with RefRed. All that is needed is to change the dependency on lr_reduction to 2.0.13

Update reduction version

---

RefRed/gui_handling/fill_stitching_table.py

We need to add more digits to the scaling factors users can enter. At the moment it's limited to 2.

Allow more decimals for manual scaling factors

---

RefRed/calculations/check_list_run_compatibility_and_display_thread.py
RefRed/calculations/check_list_run_compatibility_thread.py
RefRed/main.py
RefRed/reduction_table_handling/update_reduction_table.py
test/unit/RefRed/reduction_table_handling/test_update_reduction_table.py

Resolves [Defect 2812: Fix issue with replacing data in reduction table](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=2812)
The crash occurred when calling `DisplayPlots` from a thread created by `CheckListRunCompatibilityAndDisplayThread`. Instead, emit a signal from `CheckListRunCompatibilityAndDisplayThread` to a slot handled by the main thread and let the main thread call `DisplayThread`. This is to avoid accessing GUI elements from another thread than the main thread, see for example:
https://realpython.com/python-pyqt-qthread/#multithreading-in-pyqt-best-practices

Fix issue with replacing data in reduction table

---

RefRed/calculations/check_list_run_compatibility_thread.py
RefRed/calculations/lr_data.py
test/unit/RefRed/reduction_table_handling/test_update_reduction_table.py

Changes:
- skip auto-peak finder also when loading a different run
- also skip updating the TOF range
If the table cell being loaded already had a loaded run, use the existing configuration for peak, background, low res and TOF ranges.

Skip auto-peak finder also when loading a different run

---

RefRed/configuration/load_reduction_table_from_lconfigdataset.py
test/ui/test_reduce_and_export_data.py

pass back2 to RLData object

---

.github/workflows/test-and-deploy.yml
requirements.txt
scripts/sync_dependencies.py

Sanity check inserted in GitHub actions. It makes sure that the LiquidsReflectometer version required in the conda environment file and the pip requirements file is the same

enforce requirements in sync

---

RefRed/calculations/lr_data.py
RefRed/configuration/export_xml_config.py
RefRed/configuration/load_reduction_table_from_lconfigdataset.py
RefRed/configuration/loading_configuration.py
RefRed/interfaces/background_settings.ui
RefRed/lconfigdataset.py
RefRed/plot/background_settings.py
RefRed/preview_config/preview_config.py
RefRed/reduction/individual_reduction_settings_handler.py
RefRed/reduction/live_reduction_handler.py

Remove functional background from background settings. The backend `lr_reduction` will make the decision about functional background depending on whether the option to use two backgrounds is active or not.
Open the background settings in the UI and check that the functional background is removed and the remaining options work as before.
[Defect 4326: [REFRED] Eliminate "functional background" from the background settings](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=4326)

Remove functional background from background settings

---

RefRed/interfaces/plot2d_dialog_refl_interface.ui
RefRed/interfaces/plot_dialog_refl_interface.ui
RefRed/plot/popup_plot_1d.py
RefRed/plot/popup_plot_2d.py

The user is shown warnings when the peak range is not inside the background range. However, these warnings are obsolete as it is now valid to to define one or two background regions away from the peak range.
This PR removes the warnings shown here (red stars and text "INVALID SELECTION"):
Test changing peak and background ranges in the popup plots that appear when double-clicking either the Y vs TOF plot or the counts vs Y plot. Everything should work as before, except that there should be no red warnings about "INVALID SELECTION" shown.
[Defect 4326: [REFRED] Eliminate "functional background" …

Remove warnings about invalid background range

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/pull_request_template.md
RefRed/configuration/loading_configuration.py
RefRed/initialization/gui.py
RefRed/interfaces/deadtime_entry.py
RefRed/interfaces/deadtime_settings.py
RefRed/interfaces/deadtime_settings.ui
RefRed/interfaces/refred_main_interface.ui
RefRed/interfaces/sf_calculator_interface.ui
RefRed/main.py
RefRed/reduction/global_reduction_settings_handler.py
RefRed/sf_calculator/reduction_sf_calculator.py
RefRed/sf_calculator/sf_calculator.py
test/test_fixtures.py
test/unit/RefRed/interfaces/test_deadtime_entry.py
test/unit/RefRed/sf_calculator/test_sf_calculator.py
test/unit/RefRed/test_main.py

References [Task 4953 [REFRED] Common entry-widget for MainGui and SFCalculatorUI](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=4953)
Before running the manual tests, install the conda environment and install the source in editable mode
```bash
> conda env create --solver libmamba --name refred-dev --file ./environment.yml
> conda activate refred-dev
(refred-dev)> pip install -e .
```
Start RefRed GUI
```bash
(refred-dev)> PYTHONPATH=$(pwd):$PYTHONPATH ./scripts/start_refred.py
```
Or run tests
```bash
(refred-dev)> pytest test/unit/RefRed/test_main.py
```
+ [ ] clearly named variables (better to be verbose in variable …

Common entry-widget for MainGui and SFCalculatorUI

---

environment.yml

- [EWM #6010](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=6010)
simple update the version of the Mantid dependency to the latest Productio release
([instructions to set up the environment](https://github.com/neutrons/RefRed/blob/next/dev-docs/testing.rst#running-manual-tests-in-a-pull-request))
Start RefRed GUI
```bash
(refred-dev)> PYTHONPATH=$(pwd):$PYTHONPATH ./scripts/start_refred.py
```
Or run tests
```bash
(refred-dev)> pytest test/unit/RefRed/test_main.py
```
+ [ ] new functions and classes detailed docstrings, parameters documented

bump Mantid version

---

RefRed/sf_calculator/reduction_sf_calculator.py
test/data/sf_export_script_184975_184989.py
test/data/sf_export_script_184977_184980.py
test/unit/RefRed/sf_calculator/test_reduction_sf_calculator.py

Fix the attenuator selection for the scaling factor calculation.
The attenuator column was not passed to the calculation.

fix att selection

---

RefRed/calculations/lr_data.py
RefRed/sf_calculator/lr_data.py

Fix automated TOF range selection

Fix TOF range

---

RefRed/initialization/gui.py
RefRed/interfaces/refred_main_interface.ui

There's an angle offset available in the data reduction backend. This PR exposes it.

Add angle offset

---

RefRed/metadata/metadata_finder.py

Data files with logs that are a list of strings make the meta data browser crash. 
This PR just makes sure what is put in the table are strings.

Fix meta data table

---

.github/dependabot.yml
.github/workflows/test-and-deploy.yml
docs/release_notes.rst
environment.yml
requirements.txt

Additionally had to update github actions for CI to pass. 
Added dependabot to inform us of action updates automatically
Check all that apply:
**References:**
- Links to IBM EWM items: [Story 10179](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=10179)
- Links to related issues or pull requests: https://github.com/neutrons/LiquidsReflectometer/pull/65
([instructions to set up the environment](https://github.com/neutrons/RefRed/blob/next/docs/developer/testing.rst#running-manual-tests-in-a-pull-request))
Start RefRed GUI
```bash
(refred)> PYTHONPATH=$(pwd):$PYTHONPATH ./scripts/start_refred.py
```
Or run tests
```bash
(refred)> pytest test/unit/RefRed/test_main.py
```
+ [ ] clearly named …

update mantid to 6.12
